### ISSUE TITLE
[Feature Request] Is there any plan to increase the closed source sanatize check?

### ISSUE THREAD

**Issue by eternalsakura** [GJDuck/e9afl#3]
Is there any plan to increase the closed source sanatize check? it will be very attractive to me

**Comment by GJDuck** [comment]
Which sanitizer do you mean?

Integration with binary sanitizer(s) could be interesting but the implementation is a while off.

**Comment by eternalsakura** [comment]
such as simple asan to Detect common memory bug.

**Comment by eternalsakura** [comment]
yes, binary simple asan

**Comment by eternalsakura** [comment]
Coverage is not enough to discover more interesting security vulnerabilities

**Comment by GJDuck** [comment]
This will be implemented eventually.  However, it requires some changes to the E9Tool/E9Patch backend, such as the ability to concatenate instrumentations (something that it difficult to do with the current tool design).

**Comment by eternalsakura** [comment]
Thanks for your reply, I am looking forward to it
