### ISSUE TITLE
e9tool command failed with status (33792)

### ISSUE THREAD

**Issue by FlorinelPetrean** [GJDuck/e9afl#8]
I got the following error when trying to input a binary named test. I'm on ParrotOS if that is relevant.

$e9afl test
"/usr/share/e9afl/e9tool" -E '".plt"' -E '".plt.got"' -O2 --option --mem-granularity=4096 -o "test.afl" -M 'plugin("/usr/share/e9afl/e9AFLPlugin.so").match()' -P 'plugin("/usr/share/e9afl/e9AFLPlugin.so").patch()' -- "test"
Illegal instruction
error  : e9tool command failed with status (33792)

**Comment by GJDuck** [comment]
This might happen with older (pre-haswell) CPUs.  Try the following to check the CPU version:

    grep 'model name' /proc/cpuinfo

If that is the problem, it could be fixed by removing `-march=haswell` from the E9Patch makefiles.

**Comment by FlorinelPetrean** [comment]
Thank you! I did that and rebuilt the binary and it works!
